In [10]:
import numpy as np

In [11]:
path = np.array([[0,1,0,0,1,0],[1,0,1,1,0,1],[0,1,0,0,1,1],[0,1,0,0,1,1],[1,0,1,1,0,0],[0,1,1,1,0,0]])

In [12]:
color = np.zeros((6,6))

In [13]:
for i in range(6):
    for j in range(6):
        if path[i,j]==1:
            if color[i,i]==color[j,j]:
                color[j,j]=color[j,j]+1
print color

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]
